version: "3.9"
services:
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    command: sh -c "chown -R 777 /var/www/html && php bin/magento setup:install --base-url=http://localhost/ --db-host=mysql --db-name=magento2 --db-user=root --db-password=root --admin-firstname=Luis --admin-lastname=Ortega --admin-email=admin@tiendamia.com --admin-user=admin --admin-password=admin1234. --use-rewrites=1 --backend-frontname=admin --elasticsearch-host=http://elasticsearch:9200 && php bin/magento setup:di:compile && chmod -R 0777 var/ pub/ generated/ && service apache2 restart && tail -F anything"
    networks:
      -  es-net
    ports:
      - "80:80"
    depends_on:
      - mysql
      - elasticsearch
  provider: 
    build: 
      context: ./provider
      dockerfile: Dockerfile
    networks:
      -  es-net
    ports:
      - "3000:3000"
  mysql:
    platform: linux/amd64
    image: mysql:8.0
    networks:
      -  es-net
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'magento2'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      -  es-net
    ports:
      - 9200:9200

networks:
  es-net:
    driver: bridge