version: "3.9"
services:
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
  mysql:
    platform: linux/amd64
    image: mysql:8.0
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'magento2'